import {
  Building2,
  ShoppingCart,
  Car,
  Film,
  Zap,
  ShoppingBag,
  Home,
  Heart,
  Plane,
  Coffee,
  Gift,
  Book,
  Dumbbell,
  Smartphone,
  Wifi,
  CreditCard,
  PiggyBank,
  Wallet,
  Utensils,
  Bus,
  Fuel,
  GraduationCap,
  Stethoscope,
  PawPrint,
  type LucideIcon,
} from 'lucide-react';
import type { CategoryIconKey } from './categories-types';

export const ICON_MAP: Record<CategoryIconKey, LucideIcon> = {
  'building-2': Building2,
  'shopping-cart': ShoppingCart,
  car: Car,
  film: Film,
  zap: Zap,
  'shopping-bag': ShoppingBag,
  home: Home,
  heart: Heart,
  plane: Plane,
  coffee: Coffee,
  gift: Gift,
  book: Book,
  dumbbell: Dumbbell,
  smartphone: Smartphone,
  wifi: Wifi,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  wallet: Wallet,
  utensils: Utensils,
  bus: Bus,
  fuel: Fuel,
  'graduation-cap': GraduationCap,
  stethoscope: Stethoscope,
  'paw-print': PawPrint,
};

export const CATEGORY_ICON_KEYS = Object.keys(ICON_MAP) as CategoryIconKey[];
